language: go
go:
  - "1.11.x"
  - master

env:
  - GO111MODULE=on

install: make setup modules

script: make tests tests-cover-html build

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
