- project: gcp-project-id
  clusters:
    - name: gke-cluster-name
      zone: zone # for zonal GKE clusters
      region: region # for regional GKE clusters
      context: name-to-be-used-for-this-context
      extra_envs:
        ENV_VARIABLE: value

